% Read formatted data, write out to text files for R

dat = ten.load.data;

y = year(datetime({dat.doi}));

%dat(y>=2003) = []

%ten.write.csv(dat,'updrsIII');
ten.write.csv(dat,'akinesia');
ten.write.csv(dat,'tremor');
ten.write.csv(dat,'rigidity');
ten.write.csv(dat,'axe');

ten.write.csv1(dat,'dementia');
ten.write.csv1(dat,'Mattis');
%ten.write.csv1(dat,'frontal50');
%ten.write.csv1(dat,'updrsI');
%ten.write.csv1(dat,'updrsIV');
ten.write.csv1(dat,'hallucinations');
%ten.write.csv1(dat,'ldopaEquiv');

%ten.write.csv2(dat,'updrsII');
%ten.write.csv2(dat,'falls');

linq(dat).where(@(x) x.deceasedPark)...
   .select(@(x) fprintf('%s (%g %s)\t%s%s\t%s\n',...
      strpad(x.id,15,'post','_'),...
      year(between(datetime(x.dob,'format','dd/MM/yyyy'),datetime(x.dod,'format','dd/MM/yyyy'))),...
      x.sex,...
      x.dod,...
      iif(year(datetime(x.dod,'format','dd/MM/yyyy'))<=2004,'*',' '),...
      x.causeOfDeath));
fprintf('\n')
linq(dat).where(@(x) x.deceasedNonPark)...
   .select(@(x) fprintf('%s (%g %s)\t%s%s\t%s\n',...
      strpad(x.id,15,'post','_'),...
      year(between(datetime(x.dob,'format','dd/MM/yyyy'),datetime(x.dod,'format','dd/MM/yyyy'))),...
      x.sex,...
      x.dod,...
      iif(year(datetime(x.dod,'format','dd/MM/yyyy'))<=2004,'*',' '),...
      x.causeOfDeath));
