% Run getBasicScores3 first
if 0
   grp = grpstats(out,{'PATIENTID' 'SIDE'},'mean',...
      'DataVars',{'PSD' 'SIG' ...
      'BRADYKINESIA_OFF_CONTRA' 'BRADYKINESIA_DIFF_CONTRA' ...
      'RIGIDITY_OFF_CONTRA' 'RIGIDITY_DIFF_CONTRA' ...
      'TREMOR_OFF_CONTRA' 'TREMOR_DIFF_CONTRA' ...
      'AXIAL_OFF' 'AXIAL_DIFF'},...
      'VarNames',{'PATIENTID' 'SIDE' 'GRPCOUNT'...
      'PSD' 'SIG' ...
      'BRADYKINESIA_OFF_CONTRA' 'BRADYKINESIA_DIFF_CONTRA' ...
      'RIGIDITY_OFF_CONTRA' 'RIGIDITY_DIFF_CONTRA' ...
      'TREMOR_OFF_CONTRA' 'TREMOR_DIFF_CONTRA' ...
      'AXIAL_OFF' 'AXIAL_DIFF'});

   grp = grpstats(out,{'PATIENTID' 'CONDITION'},'mean',...
      'DataVars',{'PSD' 'SIG' ...
      'BRADYKINESIA_OFF_CONTRA' 'BRADYKINESIA_DIFF_CONTRA' ...
      'RIGIDITY_OFF_CONTRA' 'RIGIDITY_DIFF_CONTRA' ...
      'TREMOR_OFF_CONTRA' 'TREMOR_DIFF_CONTRA' ...
      'AXIAL_OFF' 'AXIAL_DIFF'},...
      'VarNames',{'PATIENTID' 'CONDITION' 'GRPCOUNT'...
      'PSD' 'SIG' ...
      'BRADYKINESIA_OFF_CONTRA' 'BRADYKINESIA_DIFF_CONTRA' ...
      'RIGIDITY_OFF_CONTRA' 'RIGIDITY_DIFF_CONTRA' ...
      'TREMOR_OFF_CONTRA' 'TREMOR_DIFF_CONTRA' ...
      'AXIAL_OFF' 'AXIAL_DIFF'});

else
   grp = grpstats(out,{'PATIENTID' 'SIDE' 'CONDITION'},'mean',...
      'DataVars',{'PSD' 'SIG' ...
      'UPDRSIII_OFF_CONTRA' 'UPDRSIII_DIFF_CONTRA' ...
      'BRADYKINESIA_OFF_CONTRA' 'BRADYKINESIA_DIFF_CONTRA' ...
      'RIGIDITY_OFF_CONTRA' 'RIGIDITY_DIFF_CONTRA' ...
      'TREMOR_OFF_CONTRA' 'TREMOR_DIFF_CONTRA' ...
      'AXIAL_OFF' 'AXIAL_DIFF' ...
      'UPDRSIV'},...
      'VarNames',{'PATIENTID' 'SIDE' 'CONDITION' 'GRPCOUNT'...
      'PSD' 'SIG' ...
      'UPDRSIII_OFF_CONTRA' 'UPDRSIII_DIFF_CONTRA' ...
      'BRADYKINESIA_OFF_CONTRA' 'BRADYKINESIA_DIFF_CONTRA' ...
      'RIGIDITY_OFF_CONTRA' 'RIGIDITY_DIFF_CONTRA' ...
      'TREMOR_OFF_CONTRA' 'TREMOR_DIFF_CONTRA' ...
      'AXIAL_OFF' 'AXIAL_DIFF' ...
      'UPDRSIV'});
   
%    grp = grpstats(out,{'PATIENTID' 'SIDE' 'CONDITION'},'mean',...
%       'DataVars',{'PSD' 'SIG' ...
%       'UPDRSIII_OFF_CONTRA' 'UPDRSIII_DIFF_CONTRA' ...
%       'BRADYKINESIA_OFF_CONTRA' 'BRADYKINESIA_DIFF_CONTRA' ...
%       'RIGIDITY_OFF_CONTRA' 'RIGIDITY_DIFF_CONTRA' ...
%       'TREMOR_OFF_CONTRA' 'TREMOR_DIFF_CONTRA' ...
%       'AXIAL_OFF' 'AXIAL_DIFF'},...
%       'VarNames',{'PATIENTID' 'SIDE' 'CONDITION' 'GRPCOUNT'...
%       'PSD' 'SIG' ...
%       'UPDRSIII_OFF_CONTRA' 'UPDRSIII_DIFF_CONTRA' ...
%       'BRADYKINESIA_OFF_CONTRA' 'BRADYKINESIA_DIFF_CONTRA' ...
%       'RIGIDITY_OFF_CONTRA' 'RIGIDITY_DIFF_CONTRA' ...
%       'TREMOR_OFF_CONTRA' 'TREMOR_DIFF_CONTRA' ...
%       'AXIAL_OFF' 'AXIAL_DIFF'});
end

indON = strcmp(grp.CONDITION,'ON');
%indLO = grp.BRADYKINESIA_OFF_CONTRA <= nanmedian(grp.BRADYKINESIA_OFF_CONTRA);
%indLO = grp.RIGIDITY_DIFF_CONTRA <= nanmedian(grp.RIGIDITY_DIFF_CONTRA);
%indLO = grp.AXIAL_OFF <= nanmedian(grp.AXIAL_OFF);
%indLO = grp.RIGIDITY_OFF_CONTRA <= nanmedian(grp.RIGIDITY_OFF_CONTRA);
%indLO = grp.TREMOR_OFF_CONTRA <= nanmedian(grp.TREMOR_OFF_CONTRA);
indLO = grp.UPDRSIV <= nanmedian(grp.UPDRSIV);

func = @nanmean;

% figure; hold on
% plot(f,mean(grp.PSD(indON,:)),'m-')
% plot(f,mean(grp.PSD(~indON,:)),'c--')

figure; hold on
plot(f,mean(grp.PSD(indLO,:)),'m-')
plot(f,mean(grp.PSD(~indLO,:)),'c--')

figure; 
subplot(211); hold on
plot(f,mean(grp.PSD(indLO,:)),'m-')
plot(f,mean(grp.PSD(~indLO,:)),'c--')
subplot(212); hold on
plot(f,mean(grp.SIG(indLO,:)),'m-')
plot(f,mean(grp.SIG(~indLO,:)),'c--')

figure; hold on
subplot(211); hold on
%  plot(f,func(grp.PSD(indLO,:)),'k-')
%  plot(f,func(grp.PSD(~indLO,:)),'k--')
plot(f,func(grp.PSD(indON&indLO,:)),'r-')
plot(f,func(grp.PSD((~indON)&indLO,:)),'b-')
plot(f,func(grp.PSD(indON&(~indLO),:)),'r--')
plot(f,func(grp.PSD((~indON)&(~indLO),:)),'b--')

subplot(212); hold on
plot(f,func(grp.PSD((~indON)&indLO,:)) - func(grp.PSD(indON&indLO,:)),'k-')
subplot(212); hold on
plot(f,func(grp.PSD((~indON)&(~indLO),:)) - func(grp.PSD(indON&(~indLO),:)),'k--')

figure; hold on
%subplot(211); hold on
% plot(f,func(grp.mean_PSD(indLO,:)),'k-')
% plot(f,func(grp.mean_PSD(~indLO,:)),'k--')
plot(f,func(grp.SIG(indON&indLO,:)),'r-')
plot(f,func(grp.SIG((~indON)&indLO,:)),'b-')
plot(f,func(grp.SIG(indON&(~indLO),:)),'r--')
plot(f,func(grp.SIG((~indON)&(~indLO),:)),'b--')

figure; 
subplot(221); hold on
plot(f,grp.PSD((~indON)&indLO,:)')
%set(gca,'xscale','log')
subplot(223); hold on
plot(f,grp.PSD((~indON)&(~indLO),:)')
%set(gca,'xscale','log')

subplot(222); hold on
plot(f,grp.PSD((indON)&indLO,:)')
%set(gca,'xscale','log')
subplot(224); hold on
plot(f,grp.PSD((indON)&(~indLO),:)')
%set(gca,'xscale','log')

%edges = prctile(grp.RIGIDITY_DIFF_CONTRA,[0 25 50 75 100]);
% edges = prctile(grp.RIGIDITY_DIFF_CONTRA,[0 33 66 100]);
edges = unique(grp.RIGIDITY_DIFF_CONTRA);
edges(1) = edges(1) - 1;
edges(end) = edges(end) + 1;
figure; hold on
c = parula(12);%['b' 'g' 'r' 'k'];
for i = 1:(numel(edges)-1)
   ind = (grp.RIGIDITY_DIFF_CONTRA>edges(i)) & (grp.RIGIDITY_DIFF_CONTRA<=edges(i+1));
   if any(ind)
      sum(ind)
      %plot(f,func(grp.PSD(ind,:)),[c(i) '-'])
      plot(f,func(grp.PSD((~indON)&ind,:)  )-...
         func(grp.PSD(indON&ind,:)),[c(i) '-'])
   end
end

temp = grp.PSD((~indON),:)';
temp2 = grp.RIGIDITY_DIFF_CONTRA((~indON));
[R,I] = sort(temp2);
%temp = bsxfun(@rdivide,temp,max(temp));
%temp = diff(temp);
s = SampledProcess(temp(:,I));
plot(s)

indON = strcmp(out.CONDITION,'ON');
temp = out.PSD((~indON),:)';
temp2 = out.RIGIDITY_DIFF_CONTRA((~indON));
[R,I] = sort(temp2);
%temp = bsxfun(@rdivide,temp,max(temp));
%temp = diff(temp);
s = SampledProcess(temp(:,I));
plot(s)
