# CSV file is generated by getBasicScores2.m
data <- read.csv(datafile)


#### HACK
data$locAP[is.nan(data$locAP)] = median(data$locAP,na.rm=T)
data$locML[is.nan(data$locML)] = median(data$locML,na.rm=T)
data$locDV[is.nan(data$locDV)] = median(data$locDV,na.rm=T)

# Keep only motor complications from UPDRSIV
#data$UPDRSIV_total <- data$UPDRSIV
#data$UPDRSIV <- data$SCORE_OFF + data$DYSKINESIA

data$DYSKINESIA = data$DYSKINESIA + as.numeric(data$DYSTONIA>0)

### NEED TO DO COND-matched here
# add item 27 to AXIAL to match Welter et al, 2015
# otherwise w/out it will match Welter et al, 2002
#data$AXIAL_OFF <- data$AXIAL_OFF + data$UPDRSIII_27_OFF
#data$AXIAL_ON <- data$AXIAL_ON + data$UPDRSIII_27_ON

data <- within(data, {
  # Ensure this is a factor
  CHANNEL <- as.factor(CHANNEL)
  # Scale to grams to keep range closer to clinical scores
  EQUIVLDOPA <- EQUIVLDOPA/1000
  LDOPA <- LDOPA/1000
  # Difference OFF - ON dopa preop scores, side-matched where appropriate
  UPDRSIII_DIFF_CONTRA <- UPDRSIII_OFF_CONTRA - UPDRSIII_ON_CONTRA
  TREMOR_DIFF_CONTRA <- TREMOR_OFF_CONTRA - TREMOR_ON_CONTRA
  BRADYKINESIA_DIFF_CONTRA <- BRADYKINESIA_OFF_CONTRA - BRADYKINESIA_ON_CONTRA
  RIGIDITY_DIFF_CONTRA <- RIGIDITY_OFF_CONTRA - RIGIDITY_ON_CONTRA
  AXIAL_DIFF <- AXIAL_OFF - AXIAL_ON
  # Fractional difference OFF - ON dopa preop scores, side-matched where appropriate
  UPDRSIII_RDIFF_CONTRA <- UPDRSIII_DIFF_CONTRA / UPDRSIII_OFF_CONTRA
  TREMOR_RDIFF_CONTRA <- TREMOR_DIFF_CONTRA / TREMOR_OFF_CONTRA
  BRADYKINESIA_RDIFF_CONTRA <- BRADYKINESIA_DIFF_CONTRA / BRADYKINESIA_OFF_CONTRA
  RIGIDITY_RDIFF_CONTRA <- RIGIDITY_DIFF_CONTRA / RIGIDITY_OFF_CONTRA
  AXIAL_RDIFF <- AXIAL_DIFF / AXIAL_OFF
  # Difference OFF - ON STIM
  UPDRSIII_STIM_DIFF <- UPDRSIII_STIM_OFF - UPDRSIII_STIM_ON
})

# Minimal data frame
df = data.frame(PATIENTID=data$PATIENTID,CONDITION=data$CONDITION)

#if (T) {#(keep_EQUIVLDOPA & keep_UPDRSIII_STIM) {
  df = data[c("PATIENTID","AGE","GENDER","DUREE_MP","SCALE","CONDITION","SIDE","CHANNEL",
              bands,
              "UPDRSIII_OFF","UPDRSIII_ON","UPDRSIII_OFF_CONTRA","UPDRSIII_COND_CONTRA","UPDRSIII_DIFF_CONTRA","UPDRSIII_RDIFF_CONTRA",
              "UPDRSIII_STIM_OFF","UPDRSIII_STIM_ON","UPDRSIII_STIM_DIFF",
              "TREMOR_OFF_CONTRA",'TREMOR_ON_CONTRA',"TREMOR_COND_CONTRA","TREMOR_DIFF_CONTRA","TREMOR_RDIFF_CONTRA",
              "BRADYKINESIA_OFF_CONTRA","BRADYKINESIA_ON_CONTRA","BRADYKINESIA_COND_CONTRA","BRADYKINESIA_DIFF_CONTRA","BRADYKINESIA_RDIFF_CONTRA",
              "RIGIDITY_OFF_CONTRA","RIGIDITY_ON_CONTRA","RIGIDITY_COND_CONTRA","RIGIDITY_DIFF_CONTRA","RIGIDITY_RDIFF_CONTRA",
              "AXIAL_OFF","AXIAL_ON","AXIAL_COND","AXIAL_DIFF","AXIAL_RDIFF",
              "DYSKINESIA","UPDRSIV","EQUIVLDOPA","LDOPA",
              "locAP","locML","locDV")]

  #df = df[complete.cases(df), ]
  
  df = overallMeanCenter(df,'UPDRSIII_STIM_ON','PATIENTID')
  df = overallMeanCenter(df,'UPDRSIII_STIM_OFF','PATIENTID')
  df = overallMeanCenter(df,'UPDRSIII_STIM_DIFF','PATIENTID')
  df = overallMeanCenter(df,'EQUIVLDOPA','PATIENTID')
  df = overallMeanCenter(df,'LDOPA','PATIENTID')
  
# } else if (keep_EQUIVLDOPA & (!keep_UPDRSIII_STIM)) {
#   df = data[c("PATIENTID","CONDITION","SIDE","CHANNEL",
#               bands,
#               "UPDRSIII_OFF","UPDRSIII_ON","UPDRSIII_OFF_CONTRA","UPDRSIII_COND_CONTRA","UPDRSIII_DIFF_CONTRA",
#               "TREMOR_OFF_CONTRA",'TREMOR_ON_CONTRA',"TREMOR_COND_CONTRA","TREMOR_DIFF_CONTRA",
#               "BRADYKINESIA_OFF_CONTRA","BRADYKINESIA_ON_CONTRA","BRADYKINESIA_COND_CONTRA","BRADYKINESIA_DIFF_CONTRA",
#               "RIGIDITY_OFF_CONTRA","RIGIDITY_ON_CONTRA","RIGIDITY_COND_CONTRA","RIGIDITY_DIFF_CONTRA",
#               "AXIAL_OFF","AXIAL_ON","AXIAL_COND","AXIAL_DIFF",
#               "UPDRSIV","EQUIVLDOPA","LDOPA",
#               "locAP","locML","locDV")]
# 
#   #df = df[complete.cases(df), ]
# 
#   df = overallMeanCenter(df,'EQUIVLDOPA','PATIENTID')
#   df = overallMeanCenter(df,'LDOPA','PATIENTID')
#   
# } else if ((!keep_EQUIVLDOPA) & keep_UPDRSIII_STIM) {
#   df = data[c("PATIENTID","CONDITION","SIDE","CHANNEL",
#               bands,
#               "UPDRSIII_OFF","UPDRSIII_ON","UPDRSIII_OFF_CONTRA","UPDRSIII_COND_CONTRA","UPDRSIII_DIFF_CONTRA",
#               "UPDRSIII_STIM_OFF","UPDRSIII_STIM_ON","UPDRSIII_STIM_DIFF",
#               "TREMOR_OFF_CONTRA",'TREMOR_ON_CONTRA',"TREMOR_COND_CONTRA","TREMOR_DIFF_CONTRA",
#               "BRADYKINESIA_OFF_CONTRA","BRADYKINESIA_ON_CONTRA","BRADYKINESIA_COND_CONTRA","BRADYKINESIA_DIFF_CONTRA",
#               "RIGIDITY_OFF_CONTRA","RIGIDITY_ON_CONTRA","RIGIDITY_COND_CONTRA","RIGIDITY_DIFF_CONTRA",
#               "AXIAL_OFF","AXIAL_ON","AXIAL_COND","AXIAL_DIFF",
#               "UPDRSIV",
#               "locAP","locML","locDV")]
#   
#   #df = df[complete.cases(df), ]
# 
#   df = overallMeanCenter(df,'UPDRSIII_STIM_ON','PATIENTID')
#   df = overallMeanCenter(df,'UPDRSIII_STIM_OFF','PATIENTID')
#   df = overallMeanCenter(df,'UPDRSIII_STIM_DIFF','PATIENTID')
# } else {
#   df = data[c("PATIENTID","CONDITION","SIDE","CHANNEL",
#               bands,
#               "UPDRSIII_OFF","UPDRSIII_ON","UPDRSIII_OFF_CONTRA","UPDRSIII_COND_CONTRA","UPDRSIII_DIFF_CONTRA",
#               "TREMOR_OFF_CONTRA",'TREMOR_ON_CONTRA',"TREMOR_COND_CONTRA","TREMOR_DIFF_CONTRA",
#               "BRADYKINESIA_OFF_CONTRA","BRADYKINESIA_ON_CONTRA","BRADYKINESIA_COND_CONTRA","BRADYKINESIA_DIFF_CONTRA",
#               "RIGIDITY_OFF_CONTRA","RIGIDITY_ON_CONTRA","RIGIDITY_COND_CONTRA","RIGIDITY_DIFF_CONTRA",
#               "AXIAL_OFF","AXIAL_ON","AXIAL_COND","AXIAL_DIFF",
#               "UPDRSIV",
#               "locAP","locML","locDV")]
#   
#   #df = df[complete.cases(df), ]
# }

df = overallMeanCenter(df,'AGE','PATIENTID')
df = overallMeanCenter(df,'DUREE_MP','PATIENTID')
df = overallMeanCenter(df,'DYSKINESIA','PATIENTID')
#df = overallMeanCenter(df,'SCORE_OFF','PATIENTID')
df = overallMeanCenter(df,'UPDRSIV','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_OFF','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_ON','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_OFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_COND_CONTRA','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_DIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_RDIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'TREMOR_OFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'TREMOR_ON_CONTRA','PATIENTID')
df = overallMeanCenter(df,'TREMOR_COND_CONTRA','PATIENTID')
df = overallMeanCenter(df,'TREMOR_DIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'TREMOR_RDIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'BRADYKINESIA_OFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'BRADYKINESIA_ON_CONTRA','PATIENTID')
df = overallMeanCenter(df,'BRADYKINESIA_COND_CONTRA','PATIENTID')
df = overallMeanCenter(df,'BRADYKINESIA_DIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'BRADYKINESIA_RDIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'RIGIDITY_OFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'RIGIDITY_ON_CONTRA','PATIENTID')
df = overallMeanCenter(df,'RIGIDITY_COND_CONTRA','PATIENTID')
df = overallMeanCenter(df,'RIGIDITY_DIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'RIGIDITY_RDIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'AXIAL_OFF','PATIENTID')
df = overallMeanCenter(df,'AXIAL_ON','PATIENTID')
df = overallMeanCenter(df,'AXIAL_COND','PATIENTID')
df = overallMeanCenter(df,'AXIAL_DIFF','PATIENTID')
df = overallMeanCenter(df,'AXIAL_RDIFF','PATIENTID')

df = overallMeanCenter(df,'locML','PATIENTID')
df = overallMeanCenter(df,'locAP','PATIENTID')
df = overallMeanCenter(df,'locDV','PATIENTID')

df = groupMeanCenter(df,'locML','PATIENTID')
df = groupMeanCenter(df,'locAP','PATIENTID')
df = groupMeanCenter(df,'locDV','PATIENTID')

#df$TREMOR_COND_CONTRA_reOFF = df$TREMOR_COND_CONTRA_oamc + mean(df$TREMOR_OFF_CONTRA,na.rm=T)
#df$RIGIDITY_COND_CONTRA_reOFF = df$RIGIDITY_COND_CONTRA_oamc + mean(df$RIGIDITY_OFF_CONTRA,na.rm=T)
#df$BRADYKINESIA_COND_CONTRA_reOFF = df$BRADYKINESIA_COND_CONTRA_oamc + mean(df$BRADYKINESIA_OFF_CONTRA,na.rm=T)
#df$AXIAL_COND_reOFF = df$AXIAL_COND_oamc + mean(df$AXIAL_OFF,na.rm=T)

#df = df[complete.cases(df), ]
#df = subset(df, SCALE!="MDS-UPDRS")

#df$CONDITION = as.numeric(df$CONDITION) - 1
#df = overallMeanCenter(df,'CONDITION','PATIENTID')