require(lme4)
require(lmerTest)
require(ggplot2)
require(car)
#require(doBy)
#require(Hmisc)
#require(languageR)
require(effects)

# Overall (grand-mean) centering (overall mean = oam)
# Take care here since the data is in long format, and the mean of a column is *not* the mean of the group means
# since data is repeated and unequal sample sizes can lead to differences
overallMeanCenter <- function(df,var,grp){
  f = as.formula(paste(var,'~',grp))
  temp <- aggregate(f,df,mean,na.action=na.pass,na.rm=T)
  df[[paste(var,'_oam',sep='')]] <- mean(temp[[var]],na.rm=T)
  df[[paste(var,'_oamc',sep='')]] = df[[var]] - df[[paste(var,'_oam',sep='')]]
  return(df) 
}

groupMeanCenter <- function(df,var,grp){
  f = as.formula(paste(var,'~',grp))
  temp <- aggregate(f,df,mean,na.action=na.pass,na.rm=T)
  names(temp)<- c(grp,paste(var,'_gm',sep=""))
  df <- merge(df,temp,by=c(grp))
  df[[paste(var,'_gmc',sep="")]] <- df[[var]] - df[[paste(var,'_gm',sep="")]]
  return(df) 
}

# CSV file is generated by getBasicScores2.m
data <- read.csv("test_RAW_STN.txt")

data <- within(data, {
  # Ensure this is a factor
  CHANNEL <- as.factor(CHANNEL)
  
  # Scale to grams to keep range closer to clinical scores
  EQUIVLDOPA <- EQUIVLDOPA/1000
  
  # Difference OFF - ON dopa preop scores, side-matched where appropriate
  UPDRSIII_DIFF_CONTRA <- UPDRSIII_OFF_CONTRA - UPDRSIII_ON_CONTRA
  TREMOR_DIFF_CONTRA <- TREMOR_OFF_CONTRA - TREMOR_ON_CONTRA
  BRADYKINESIA_DIFF_CONTRA <- BRADYKINESIA_OFF_CONTRA - BRADYKINESIA_ON_CONTRA
  RIGIDITY_DIFF_CONTRA <- RIGIDITY_OFF_CONTRA - RIGIDITY_ON_CONTRA
  AXIAL_DIFF <- AXIAL_OFF - AXIAL_ON
})

df = data.frame(PATIENTID=data$PATIENTID,CONDITION=data$CONDITION)
# Minimal data frame
df = data[c("PATIENTID","CONDITION","SIDE","CHANNEL",
            "f_4_8","f_8_12","f_12_20","f_20_30","f_8_35","f_60_90",
            "UPDRSIII_OFF","UPDRSIII_OFF_CONTRA","UPDRSIII_COND_CONTRA","UPDRSIII_DIFF_CONTRA",
            "TREMOR_OFF_CONTRA","TREMOR_COND_CONTRA","TREMOR_DIFF_CONTRA",
            "BRADYKINESIA_OFF_CONTRA","BRADYKINESIA_COND_CONTRA","BRADYKINESIA_DIFF_CONTRA",
            "RIGIDITY_OFF_CONTRA","RIGIDITY_COND_CONTRA","RIGIDITY_DIFF_CONTRA",
            "AXIAL_OFF","AXIAL_COND","AXIAL_DIFF",
            "UPDRSIV","EQUIVLDOPA",
            "locAP","locML","locDV")]

df = overallMeanCenter(df,'UPDRSIV','PATIENTID')
df = overallMeanCenter(df,'EQUIVLDOPA','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_OFF','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_OFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_COND_CONTRA','PATIENTID')
df = overallMeanCenter(df,'UPDRSIII_DIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'TREMOR_OFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'TREMOR_COND_CONTRA','PATIENTID')
df = overallMeanCenter(df,'TREMOR_DIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'BRADYKINESIA_OFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'BRADYKINESIA_COND_CONTRA','PATIENTID')
df = overallMeanCenter(df,'BRADYKINESIA_DIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'RIGIDITY_OFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'RIGIDITY_COND_CONTRA','PATIENTID')
df = overallMeanCenter(df,'RIGIDITY_DIFF_CONTRA','PATIENTID')
df = overallMeanCenter(df,'AXIAL_OFF','PATIENTID')
df = overallMeanCenter(df,'AXIAL_COND','PATIENTID')
df = overallMeanCenter(df,'AXIAL_DIFF','PATIENTID')

df = groupMeanCenter(df,'locML','PATIENTID')
df = groupMeanCenter(df,'locAP','PATIENTID')
df = groupMeanCenter(df,'locDV','PATIENTID')

df = df[complete.cases(df), ]

f = as.formula("10*log10(f_60_90) ~ 
               CONDITION*(
               TREMOR_DIFF_CONTRA_oamc + BRADYKINESIA_DIFF_CONTRA_oamc + RIGIDITY_DIFF_CONTRA_oamc + AXIAL_DIFF_oamc) + 
               UPDRSIV_oamc + EQUIVLDOPA_oamc + 
               TREMOR_OFF_CONTRA_oamc + BRADYKINESIA_OFF_CONTRA_oamc + RIGIDITY_OFF_CONTRA_oamc + AXIAL_OFF_oamc + 
               locAP_gmc + locML_gmc + locDV_gmc + 
               locAP_gm + locML_gm + locDV_gm + 
               SIDE + 
               (1+CONDITION||PATIENTID/SIDE)
               ")


f = as.formula("10*log10(f_4_8) ~ 
               CONDITION*(
               TREMOR_DIFF_CONTRA_oamc + BRADYKINESIA_DIFF_CONTRA_oamc + RIGIDITY_DIFF_CONTRA_oamc + AXIAL_DIFF_oamc) + 
               UPDRSIV_oamc + EQUIVLDOPA_oamc + 
               UPDRSIII_OFF_CONTRA_oamc + 
               locAP_gmc + locML_gmc + locDV_gmc + 
               locAP_gm + locML_gm + locDV_gm + 
               SIDE + 
               (1 + CONDITION|PATIENTID/SIDE)
               ")
f = as.formula("10*log10(f_4_8) ~ CONDITION*(UPDRSIII_OFF_oamc + UPDRSIV_oamc + EQUIVLDOPA_oamc) +
               #UPDRSIII_COND_CONTRA_oamc + 
               locAP_gmc + locML_gmc + locDV_gmc +
               locAP_gm + locML_gm + locDV_gm +
               SIDE +
               (1 + CONDITION|PATIENTID/SIDE)
               ")
f = as.formula("10*log10(f_60_90) ~ CONDITION*(UPDRSIII_OFF_CONTRA_oamc + UPDRSIII_DIFF_CONTRA_oamc + UPDRSIV_oamc + EQUIVLDOPA_oamc) +
               locAP_gmc + locML_gmc + locDV_gmc +
               locAP_gm + locML_gm + locDV_gm +
               SIDE +
               (1 + CONDITION|PATIENTID/SIDE)
               ")
f = as.formula("10*log10(f_4_8) ~ 
               CONDITION*(
               TREMOR_DIFF_CONTRA_oamc + BRADYKINESIA_DIFF_CONTRA_oamc + RIGIDITY_DIFF_CONTRA_oamc + AXIAL_DIFF_oamc + 
               UPDRSIV_oamc + EQUIVLDOPA_oamc + 
               TREMOR_OFF_CONTRA_oamc + BRADYKINESIA_OFF_CONTRA_oamc + RIGIDITY_OFF_CONTRA_oamc + AXIAL_OFF_oamc) + 
               locAP_gmc + poly(locML_gmc,2) + locDV_gmc + 
               locAP_gm + locML_gm + locDV_gm + 
               SIDE + 
               (1+CONDITION|PATIENTID/SIDE)
               ")
m0 = lmer(f,data=df,REML=T,control=lmerControl(optCtrl=list(maxfun=100000)))

m = m0
ddf = "Kenward-Roger"#"Satterthwaite" #"Kenward-Roger"#
print(summary(m,ddf=ddf),correlation=FALSE)
anova(m,ddf=ddf)
qqPlot(resid(m), main="Q-Q plot for residuals")

ggplot(df, aes(x = CONDITION, y = 10*log10(f_4_8), colour = SIDE)) +
  facet_wrap(~PATIENTID, nrow=7) +
  geom_point() +
  theme_classic() +
  geom_line(data = cbind(df, pred = predict(m)), aes(y = pred)) +
  theme(legend.position = "none")

ggplot(df, aes(x = locAP_gmc, y = 10*log10(f_4_8), colour = SIDE)) +
  facet_wrap(~PATIENTID, nrow=7) +
  geom_point() +
  theme_classic() +
  geom_line(data = cbind(df, pred = predict(m)), aes(y = pred)) +
  theme(legend.position = "none")

plot(effect("locAP_gmc",m,partial.residuals=T))
plot(effect("locML_gmc",m,partial.residuals=T))
plot(effect("locDV_gmc",m,partial.residuals=T))
plot(effect("CONDITION*UPDRSIV_oamc",m,partial.residuals=T))
plot(effect("CONDITION*EQUIVLDOPA_oamc",m,partial.residuals=T))
plot(effect("CONDITION*UPDRSIII_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*TREMOR_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*BRADYKINESIA_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*RIGIDITY_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*RIGIDITY_OFF_CONTRA_oamc", m,partial.residuals=T))

ggplot(df, aes(x = BRADYKINESIA_DIFF_CONTRA_oamc, y = 10*log10(f_4_8), colour = CONDITION)) +
  facet_wrap(~PATIENTID, nrow=7) +
  geom_point() +
  theme_classic() +
  geom_line(data = cbind(df, pred = predict(m)), aes(y = pred)) +
  theme(legend.position = "none")

library(lattice)
xyplot(resid(m) ~ fitted(m)|PATIENTID, m@frame)
