require(lme4)
require(lmerTest)
require(ggplot2)
require(car)
#require(doBy)
#require(Hmisc)
#require(languageR)
require(effects)

# CSV file is generated by getBasicScores2.m
data <- read.csv("test_DETAIL_STN.txt")
data <- within(data, {
  # Ensure this is a factor
  CHANNEL <- as.factor(CHANNEL)
  # Scale to grams to keep range closer to clinical scores
  EQUIVLDOPA <- EQUIVLDOPA/1000
  
  # Difference OFF - ON dopa preop scores
  UPDRSIII_DIFF_CONTRA <- UPDRSIII_OFF_CONTRA - UPDRSIII_ON_CONTRA
  TREMOR_DIFF_CONTRA <- TREMOR_OFF_CONTRA - TREMOR_ON_CONTRA
  BRADYKINESIA_DIFF_CONTRA <- BRADYKINESIA_OFF_CONTRA - BRADYKINESIA_ON_CONTRA
  RIGIDITY_DIFF_CONTRA <- RIGIDITY_OFF_CONTRA - RIGIDITY_ON_CONTRA
  AXIAL_DIFF <- AXIAL_OFF - AXIAL_ON
})

df = data.frame(PATIENTID=data$PATIENTID,CONDITION=data$)

# Grand-mean centering (overall mean = oam)
# Take care here since the data is in long format, and the mean of a column is *not* the mean of the group means
# since data is repeated and unequal sample sizes can lead to differences
temp <- aggregate(EQUIVLDOPA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','EQUIVLDOPA_oam')
meanofmeans <- mean(temp$EQUIVLDOPA_oam,na.rm=T)
temp$EQUIVLDOPA_oamc = temp$EQUIVLDOPA_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(UPDRSIV ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','UPDRSIV_oam')
meanofmeans <- mean(temp$UPDRSIV_oam,na.rm=T)
temp$UPDRSIV_oamc = temp$UPDRSIV_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(UPDRSIII_DIFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','UPDRSIII_DIFF_CONTRA_oam')
meanofmeans <- mean(temp$UPDRSIII_DIFF_CONTRA_oam,na.rm=T)
temp$UPDRSIII_DIFF_CONTRA_oamc = temp$UPDRSIII_DIFF_CONTRA_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(TREMOR_DIFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','TREMOR_DIFF_CONTRA_oam')
meanofmeans <- mean(temp$TREMOR_DIFF_CONTRA_oam,na.rm=T)
temp$TREMOR_DIFF_CONTRA_oamc = temp$TREMOR_DIFF_CONTRA_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(BRADYKINESIA_DIFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','BRADYKINESIA_DIFF_CONTRA_oam')
meanofmeans <- mean(temp$BRADYKINESIA_DIFF_CONTRA_oam,na.rm=T)
temp$BRADYKINESIA_DIFF_CONTRA_oamc = temp$BRADYKINESIA_DIFF_CONTRA_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(RIGIDITY_DIFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','RIGIDITY_DIFF_CONTRA_oam')
meanofmeans <- mean(temp$RIGIDITY_DIFF_CONTRA_oam,na.rm=T)
temp$RIGIDITY_DIFF_CONTRA_oamc = temp$RIGIDITY_DIFF_CONTRA_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(AXIAL_DIFF ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','AXIAL_DIFF_oam')
meanofmeans <- mean(temp$AXIAL_DIFF_oam,na.rm=T)
temp$AXIAL_DIFF_oamc = temp$AXIAL_DIFF_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(locML ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locML_oam')
meanofmeans <- mean(temp$locML_oam,na.rm=T)
temp$locML_oamc = temp$locML_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(locAP ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locAP_oam')
meanofmeans <- mean(temp$locAP_oam,na.rm=T)
temp$locAP_oamc = temp$locAP_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

temp <- aggregate(locDV ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locDV_oam')
meanofmeans <- mean(temp$locDV_oam,na.rm=T)
temp$locDV_oamc = temp$locDV_oam - meanofmeans
data <- merge(data, temp, by = c('PATIENTID'))

# Group-mean centered (gmc)
temp <- aggregate(locML ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locML_gm')
data <- merge(data, temp, by = c('PATIENTID'))
data$locML_gmc <- data$locML - data$locML_gm

temp <- aggregate(locAP ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locAP_gm')
data <- merge(data, temp, by = c('PATIENTID'))
data$locAP_gmc <- data$locAP - data$locAP_gm

temp <- aggregate(locDV ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locDV_gm')
data <- merge(data, temp, by = c('PATIENTID'))
data$locDV_gmc <- data$locDV - data$locDV_gm

# Minimal data frame
df = data[c("PATIENTID","CONDITION","SIDE","CHANNEL",
            "f_4_8","f_8_12","f_12_20","f_20_30","f_60_90",
            #"UPDRSIV","UPDRSIV_oam","UPDRSIV_oamc",
            #"EQUIVLDOPA","EQUIVLDOPA_oam","EQUIVLDOPA_oamc",
            "UPDRSIII_DIFF_CONTRA","UPDRSIII_DIFF_CONTRA_oam","UPDRSIII_DIFF_CONTRA_oamc",
            "TREMOR_DIFF_CONTRA","TREMOR_DIFF_CONTRA_oam","TREMOR_DIFF_CONTRA_oamc",
            "BRADYKINESIA_DIFF_CONTRA","BRADYKINESIA_DIFF_CONTRA_oam","BRADYKINESIA_DIFF_CONTRA_oamc",
            "RIGIDITY_DIFF_CONTRA","RIGIDITY_DIFF_CONTRA_oam","RIGIDITY_DIFF_CONTRA_oamc",
            "AXIAL_DIFF","AXIAL_DIFF_oam","AXIAL_DIFF_oamc",
            "locAP_oamc","locAP_gm","locAP_gmc","locML_oamc","locML_gm","locML_gmc","locDV_oamc","locDV_gm","locDV_gmc")]

df = df[complete.cases(df), ]

f = as.formula("10*log10(f_20_30) ~ CONDITION*(TREMOR_DIFF_CONTRA_oamc + BRADYKINESIA_DIFF_CONTRA_oamc + RIGIDITY_DIFF_CONTRA_oamc + AXIAL_DIFF_oamc) + 
              locAP_gmc + locML_gmc + locDV_gmc + 
              locAP_gm + locML_gm + locDV_gm + 
              #UPDRSIV + EQUIVLDOPA_oamc +
              #SIDE + 
              #(1|PATIENTID/SIDE/CHANNEL)
              #(1|PATIENTID/SIDE)
              #(1|PATIENTID/CHANNEL) #***
              #(1 + CONDITION|PATIENTID) #***
              #(1 + CONDITION|PATIENTID/SIDE)
              #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID)
              #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc + locAP_gm + locML_gm + locDV_gm|PATIENTID)
              (1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID/SIDE)
               ")
# f = as.formula("10*log10(f_4_8) ~ CONDITION*(UPDRSIII_DIFF_CONTRA_oamc) + 
#               locAP_gmc + locML_gmc + locDV_gmc + 
#                locAP_gm + locML_gm + locDV_gm + 
#                #UPDRSIV + EQUIVLDOPA_oamc +
#                #SIDE + 
#                #(1|PATIENTID/SIDE/CHANNEL)
#                #(1|PATIENTID/SIDE)
#                #(1|PATIENTID/CHANNEL) #***
#                #(1 + CONDITION|PATIENTID) #***
#                #(1 + CONDITION|PATIENTID/SIDE)
#                #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID)
#                #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc + locAP_gm + locML_gm + locDV_gm|PATIENTID)
#                (1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID/SIDE)
#                ")
# f = as.formula("10*log10(f_60_90) ~ CONDITION*(TREMOR_DIFF_CONTRA_oamc + BRADYKINESIA_DIFF_CONTRA_oamc + RIGIDITY_DIFF_CONTRA_oamc + AXIAL_DIFF_oamc) + 
#               locAP_oamc + locML_oamc + locDV_oamc + 
#               #UPDRSIV + EQUIVLDOPA_oamc +
#               SIDE + 
#               #(1|PATIENTID/SIDE/CHANNEL)
#               #(1|PATIENTID/SIDE)
#               #(1|PATIENTID/CHANNEL) #***
#               #(1 + CONDITION|PATIENTID) #***
#               #(1 + CONDITION|PATIENTID/SIDE)
#               (1 + CONDITION + locAP_oamc + locML_oamc + locDV_oamc|PATIENTID)
#               #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc + locAP_gm + locML_gm + locDV_gm|PATIENTID)
#               #(1 + CONDITION + locAP_oamc + locML_oamc + locDV_oamc|PATIENTID/SIDE)
#                ")

m0 = lmer(f,data=df,REML=T,control=lmerControl(optCtrl=list(maxfun=20000) ))

m = m0

ddf = "Satterthwaite" #"Kenward-Roger"
print(summary(m,ddf=ddf),correlation=FALSE)
anova(m,ddf=ddf)

ef <- allEffects(m)
print(ef)
plot(ef,confint=T)

#m1 <- mixed(f,df, method = "S")

ggplot(df, aes(x = locAP_gmc, y = 10*log10(f_20_30), colour = SIDE)) +
  facet_wrap(~PATIENTID, nrow=7) +
  geom_point() +
  theme_classic() +
  geom_line(data = cbind(df, pred = predict(m)), aes(y = pred)) +
  theme(legend.position = "none")

plot(effect("locAP_gmc",m,partial.residuals=T))
plot(effect("CONDITION*BRADYKINESIA_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*RIGIDITY_DIFF_CONTRA_oamc", m,partial.residuals=T))

ggplot(df, aes(x = BRADYKINESIA_DIFF_CONTRA_oamc, y = 10*log10(f_4_8), colour = CONDITION)) +
  facet_wrap(~PATIENTID, nrow=7) +
  geom_point() +
  theme_classic() +
  geom_line(data = cbind(df, pred = predict(m)), aes(y = pred)) +
  theme(legend.position = "none")