require(lme4)
require(lmerTest)
require(ggplot2)
require(car)
#require(doBy)
#require(Hmisc)
#require(languageR)
require(effects)

# CSV file is generated by getBasicScores2.m
data <- read.csv("test_RAW_STN.txt")

data <- within(data, {
  # Ensure this is a factor
  CHANNEL <- as.factor(CHANNEL)

    # Scale to grams to keep range closer to clinical scores
  EQUIVLDOPA <- EQUIVLDOPA/1000
  
  # Difference OFF - ON dopa preop scores, side-matched where appropriate
  UPDRSIII_DIFF_CONTRA <- UPDRSIII_OFF_CONTRA - UPDRSIII_ON_CONTRA
  TREMOR_DIFF_CONTRA <- TREMOR_OFF_CONTRA - TREMOR_ON_CONTRA
  BRADYKINESIA_DIFF_CONTRA <- BRADYKINESIA_OFF_CONTRA - BRADYKINESIA_ON_CONTRA
  RIGIDITY_DIFF_CONTRA <- RIGIDITY_OFF_CONTRA - RIGIDITY_ON_CONTRA
  AXIAL_DIFF <- AXIAL_OFF - AXIAL_ON
})


df = data.frame(PATIENTID=data$PATIENTID,CONDITION=data$CONDITION)

# Grand-mean centering (overall mean = oam)
# Take care here since the data is in long format, and the mean of a column is *not* the mean of the group means
# since data is repeated and unequal sample sizes can lead to differences
temp <- aggregate(EQUIVLDOPA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','EQUIVLDOPA_oam')
data$EQUIVLDOPA_oam <- mean(temp$EQUIVLDOPA_oam,na.rm=T)
data$EQUIVLDOPA_oamc = data$EQUIVLDOPA - data$EQUIVLDOPA_oam

grandMeanCenter <- function(df,var,grp){
  f = as.formula(paste(var,'~',grp))
  temp <- aggregate(f,df,mean,na.action=na.pass,na.rm=T)
  names(temp)<- c('PATIENTID','EQUIVLDOPA_oam')
  data$EQUIVLDOPA_oam <- mean(temp$EQUIVLDOPA_oam,na.rm=T)
  data$EQUIVLDOPA_oamc = data$EQUIVLDOPA - data$EQUIVLDOPA_oam
  
  return(df) 
}

temp <- aggregate(UPDRSIV ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','UPDRSIV_oam')
data$UPDRSIV_oam <- mean(temp$UPDRSIV_oam,na.rm=T)
data$UPDRSIV_oamc = data$UPDRSIV - data$UPDRSIV_oam

temp <- aggregate(UPDRSIII_OFF ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','UPDRSIII_OFF_oam')
data$UPDRSIII_OFF_oam <- mean(temp$UPDRSIII_OFF_oam,na.rm=T)
data$UPDRSIII_OFF_oamc = data$UPDRSIII_OFF - data$UPDRSIII_OFF_oam

temp <- aggregate(UPDRSIII_OFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','UPDRSIII_OFF_CONTRA_oam')
data$UPDRSIII_OFF_CONTRA_oam <- mean(temp$UPDRSIII_OFF_CONTRA_oam,na.rm=T)
data$UPDRSIII_OFF_CONTRA_oamc = data$UPDRSIII_OFF_CONTRA - data$UPDRSIII_OFF_CONTRA_oam

temp <- aggregate(UPDRSIII_COND_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','UPDRSIII_COND_CONTRA_oam')
data$UPDRSIII_COND_CONTRA_oam <- mean(temp$UPDRSIII_COND_CONTRA_oam,na.rm=T)
data$UPDRSIII_COND_CONTRA_oamc = data$UPDRSIII_COND_CONTRA - data$UPDRSIII_COND_CONTRA_oam

temp <- aggregate(UPDRSIII_DIFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','UPDRSIII_DIFF_CONTRA_oam')
data$UPDRSIII_DIFF_CONTRA_oam <- mean(temp$UPDRSIII_DIFF_CONTRA_oam,na.rm=T)
data$UPDRSIII_DIFF_CONTRA_oamc = data$UPDRSIII_DIFF_CONTRA - data$UPDRSIII_DIFF_CONTRA_oam

temp <- aggregate(TREMOR_COND_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','TREMOR_COND_CONTRA_oam')
data$TREMOR_COND_CONTRA_oam <- mean(temp$TREMOR_COND_CONTRA_oam,na.rm=T)
data$TREMOR_COND_CONTRA_oamc = data$TREMOR_COND_CONTRA - data$TREMOR_COND_CONTRA_oam

temp <- aggregate(TREMOR_DIFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','TREMOR_DIFF_CONTRA_oam')
data$TREMOR_DIFF_CONTRA_oam <- mean(temp$TREMOR_DIFF_CONTRA_oam,na.rm=T)
data$TREMOR_DIFF_CONTRA_oamc = data$TREMOR_DIFF_CONTRA - data$TREMOR_DIFF_CONTRA_oam

temp <- aggregate(BRADYKINESIA_COND_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','BRADYKINESIA_COND_CONTRA_oam')
data$BRADYKINESIA_COND_CONTRA_oam <- mean(temp$BRADYKINESIA_COND_CONTRA_oam,na.rm=T)
data$BRADYKINESIA_COND_CONTRA_oamc = data$BRADYKINESIA_COND_CONTRA - data$BRADYKINESIA_COND_CONTRA_oam

temp <- aggregate(BRADYKINESIA_DIFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','BRADYKINESIA_DIFF_CONTRA_oam')
data$BRADYKINESIA_DIFF_CONTRA_oam <- mean(temp$BRADYKINESIA_DIFF_CONTRA_oam,na.rm=T)
data$BRADYKINESIA_DIFF_CONTRA_oamc = data$BRADYKINESIA_DIFF_CONTRA - data$BRADYKINESIA_DIFF_CONTRA_oam

temp <- aggregate(RIGIDITY_COND_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','RIGIDITY_COND_CONTRA_oam')
data$RIGIDITY_COND_CONTRA_oam <- mean(temp$RIGIDITY_COND_CONTRA_oam,na.rm=T)
data$RIGIDITY_COND_CONTRA_oamc = data$RIGIDITY_COND_CONTRA - data$RIGIDITY_COND_CONTRA_oam

temp <- aggregate(RIGIDITY_DIFF_CONTRA ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','RIGIDITY_DIFF_CONTRA_oam')
data$RIGIDITY_DIFF_CONTRA_oam <- mean(temp$RIGIDITY_DIFF_CONTRA_oam,na.rm=T)
data$RIGIDITY_DIFF_CONTRA_oamc = data$RIGIDITY_DIFF_CONTRA - data$RIGIDITY_DIFF_CONTRA_oam

temp <- aggregate(AXIAL_COND ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','AXIAL_COND_oam')
data$AXIAL_COND_oam <- mean(temp$AXIAL_COND_oam,na.rm=T)
data$AXIAL_COND_oamc = data$AXIAL_COND - data$AXIAL_COND_oam

temp <- aggregate(AXIAL_DIFF ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','AXIAL_DIFF_oam')
data$AXIAL_DIFF_oam <- mean(temp$AXIAL_DIFF_oam,na.rm=T)
data$AXIAL_DIFF_oamc = data$AXIAL_DIFF - data$AXIAL_DIFF_oam

temp <- aggregate(locML ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locML_oam')
data$locML_oam <- mean(temp$locML_oam,na.rm=T)
data$locML_oamc = data$locML - data$locML_oam

temp <- aggregate(locAP ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locAP_oam')
data$locAP_oam <- mean(temp$locAP_oam,na.rm=T)
data$locAP_oamc = data$locAP - data$locAP_oam

temp <- aggregate(locDV ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locDV_oam')
data$locDV_oam <- mean(temp$locDV_oam,na.rm=T)
data$locDV_oamc = data$locDV - data$locDV_oam

# Group-mean centered (gmc)
temp <- aggregate(locML ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locML_gm')
data <- merge(data, temp, by = c('PATIENTID'))
data$locML_gmc <- data$locML - data$locML_gm

temp <- aggregate(locAP ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locAP_gm')
data <- merge(data, temp, by = c('PATIENTID'))
data$locAP_gmc <- data$locAP - data$locAP_gm

temp <- aggregate(locDV ~ PATIENTID,data,mean,na.action=na.pass,na.rm=T)
names(temp)<- c('PATIENTID','locDV_gm')
data <- merge(data, temp, by = c('PATIENTID'))
data$locDV_gmc <- data$locDV - data$locDV_gm

# Minimal data frame
df = data[c("PATIENTID","CONDITION","SIDE","CHANNEL",
            "f_4_8","f_8_12","f_12_20","f_20_30","f_8_35","f_60_90",
            "UPDRSIV","UPDRSIV_oam","UPDRSIV_oamc",
            "EQUIVLDOPA","EQUIVLDOPA_oam","EQUIVLDOPA_oamc",
            "UPDRSIII_OFF_CONTRA","UPDRSIII_OFF_CONTRA_oam","UPDRSIII_OFF_CONTRA_oamc",
            "UPDRSIII_OFF","UPDRSIII_OFF_oam","UPDRSIII_OFF_oamc",
            "UPDRSIII_COND_CONTRA","UPDRSIII_COND_CONTRA_oam","UPDRSIII_COND_CONTRA_oamc",
            "UPDRSIII_DIFF_CONTRA","UPDRSIII_DIFF_CONTRA_oam","UPDRSIII_DIFF_CONTRA_oamc",
            "TREMOR_COND_CONTRA","TREMOR_COND_CONTRA_oam","TREMOR_COND_CONTRA_oamc",
            "TREMOR_DIFF_CONTRA","TREMOR_DIFF_CONTRA_oam","TREMOR_DIFF_CONTRA_oamc",
            "BRADYKINESIA_COND_CONTRA","BRADYKINESIA_COND_CONTRA_oam","BRADYKINESIA_COND_CONTRA_oamc",
            "BRADYKINESIA_DIFF_CONTRA","BRADYKINESIA_DIFF_CONTRA_oam","BRADYKINESIA_DIFF_CONTRA_oamc",
            "RIGIDITY_COND_CONTRA","RIGIDITY_COND_CONTRA_oam","RIGIDITY_COND_CONTRA_oamc",
            "RIGIDITY_DIFF_CONTRA","RIGIDITY_DIFF_CONTRA_oam","RIGIDITY_DIFF_CONTRA_oamc",
            "AXIAL_COND","AXIAL_COND_oam","AXIAL_COND_oamc",
            "AXIAL_DIFF","AXIAL_DIFF_oam","AXIAL_DIFF_oamc",
            "locAP_oamc","locAP_gm","locAP_gmc","locML_oamc","locML_gm","locML_gmc","locDV_oamc","locDV_gm","locDV_gmc")]

df = df[complete.cases(df), ]

f = as.formula("10*log10(f_8_12) ~ CONDITION*(TREMOR_DIFF_CONTRA_oamc + BRADYKINESIA_DIFF_CONTRA_oamc + RIGIDITY_DIFF_CONTRA_oamc + AXIAL_DIFF_oamc + UPDRSIV_oamc + EQUIVLDOPA_oamc) + 
              locAP_gmc + locML_gmc + locDV_gmc + 
              locAP_gm + locML_gm + locDV_gm + 
              #UPDRSIV + EQUIVLDOPA_oamc +
              SIDE + 
              #(1|PATIENTID/SIDE/CHANNEL)
              #(1|PATIENTID/SIDE)
              #(1|PATIENTID/CHANNEL) #***
              #(1 + CONDITION|PATIENTID) #***
              (1 + CONDITION|PATIENTID/SIDE)
              #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID)
              #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc + locAP_gm + locML_gm + locDV_gm|PATIENTID)
              #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID/SIDE)
               ")
f = as.formula("10*log10(f_4_8) ~ CONDITION*(
              TREMOR_DIFF_CONTRA_oamc + BRADYKINESIA_DIFF_CONTRA_oamc + RIGIDITY_DIFF_CONTRA_oamc + AXIAL_DIFF_oamc + 
              UPDRSIV_oamc + EQUIVLDOPA_oamc) + 
              TREMOR_COND_CONTRA_oamc + BRADYKINESIA_COND_CONTRA_oamc + RIGIDITY_COND_CONTRA_oamc + AXIAL_COND_oamc + 
              locAP_gmc + locML_gmc + locDV_gmc + 
               locAP_gm + locML_gm + locDV_gm + 
               #UPDRSIV + EQUIVLDOPA_oamc +
               SIDE + 
               #(1|PATIENTID/SIDE/CHANNEL)
               #(1|PATIENTID/SIDE)
               #(1|PATIENTID/CHANNEL) #***
               #(1 + CONDITION|PATIENTID) #***
               (1 + CONDITION|PATIENTID/SIDE)
               #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID)
               #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc + locAP_gm + locML_gm + locDV_gm|PATIENTID)
               #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID/SIDE)
               ")
f = as.formula("10*log10(f_4_8) ~ CONDITION*(UPDRSIII_OFF_oamc + UPDRSIV_oamc + EQUIVLDOPA_oamc) +
              #UPDRSIII_COND_CONTRA_oamc + 
              locAP_gmc + locML_gmc + locDV_gmc +
              locAP_gm + locML_gm + locDV_gm +
              SIDE +
              (1 + CONDITION|PATIENTID/SIDE)
               ")
f = as.formula("10*log10(f_12_20) ~ CONDITION*(UPDRSIII_OFF_CONTRA_oamc + UPDRSIII_DIFF_CONTRA_oamc + UPDRSIV_oamc + EQUIVLDOPA_oamc) +
              locAP_gmc + locML_gmc + locDV_gmc +
              locAP_gm + locML_gm + locDV_gm +
              SIDE +
              (1 + CONDITION|PATIENTID/SIDE)
               ")
# f = as.formula("10*log10(f_4_8) ~ CONDITION*(UPDRSIII_DIFF_CONTRA_oamc) + 
#               locAP_gmc + locML_gmc + locDV_gmc + 
#                locAP_gm + locML_gm + locDV_gm + 
#                #UPDRSIV + EQUIVLDOPA_oamc +
#                #SIDE + 
#                #(1|PATIENTID/SIDE/CHANNEL)
#                #(1|PATIENTID/SIDE)
#                #(1|PATIENTID/CHANNEL) #***
#                #(1 + CONDITION|PATIENTID) #***
#                #(1 + CONDITION|PATIENTID/SIDE)
#                #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID)
#                #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc + locAP_gm + locML_gm + locDV_gm|PATIENTID)
#                (1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc|PATIENTID/SIDE)
#                ")
# f = as.formula("10*log10(f_60_90) ~ CONDITION*(TREMOR_DIFF_CONTRA_oamc + BRADYKINESIA_DIFF_CONTRA_oamc + RIGIDITY_DIFF_CONTRA_oamc + AXIAL_DIFF_oamc) + 
#               locAP_oamc + locML_oamc + locDV_oamc + 
#               #UPDRSIV + EQUIVLDOPA_oamc +
#               SIDE + 
#               #(1|PATIENTID/SIDE/CHANNEL)
#               #(1|PATIENTID/SIDE)
#               #(1|PATIENTID/CHANNEL) #***
#               #(1 + CONDITION|PATIENTID) #***
#               #(1 + CONDITION|PATIENTID/SIDE)
#               (1 + CONDITION + locAP_oamc + locML_oamc + locDV_oamc|PATIENTID)
#               #(1 + CONDITION + locAP_gmc + locML_gmc + locDV_gmc + locAP_gm + locML_gm + locDV_gm|PATIENTID)
#               #(1 + CONDITION + locAP_oamc + locML_oamc + locDV_oamc|PATIENTID/SIDE)
#                ")

m0 = lmer(f,data=df,REML=T,control=lmerControl(optCtrl=list(maxfun=50000) ))

m = m0

ddf = "Satterthwaite" #"Kenward-Roger"
print(summary(m,ddf=ddf),correlation=FALSE)
anova(m,ddf=ddf)
qqPlot(resid(m), main="Q-Q plot for residuals")

ef <- allEffects(m)
print(ef)
plot(ef,confint=T)

#m1 <- mixed(f,df, method = "S")

ggplot(df, aes(x = locAP_gmc, y = 10*log10(f_4_8), colour = SIDE)) +
  facet_wrap(~PATIENTID, nrow=7) +
  geom_point() +
  theme_classic() +
  geom_line(data = cbind(df, pred = predict(m)), aes(y = pred)) +
  theme(legend.position = "none")

plot(effect("locAP_gmc",m,partial.residuals=T))
plot(effect("locML_gmc",m,partial.residuals=T))
plot(effect("locDV_gmc",m,partial.residuals=T))
plot(effect("CONDITION*UPDRSIV_oamc",m,partial.residuals=T))
plot(effect("CONDITION*EQUIVLDOPA_oamc",m,partial.residuals=T))
plot(effect("CONDITION*UPDRSIII_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*TREMOR_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*BRADYKINESIA_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*RIGIDITY_DIFF_CONTRA_oamc", m,partial.residuals=T))
plot(effect("CONDITION*RIGIDITY_COND_CONTRA_oamc", m,partial.residuals=T))

ggplot(df, aes(x = BRADYKINESIA_DIFF_CONTRA_oamc, y = 10*log10(f_12_20), colour = CONDITION)) +
  facet_wrap(~PATIENTID, nrow=7) +
  geom_point() +
  theme_classic() +
  geom_line(data = cbind(df, pred = predict(m)), aes(y = pred)) +
  theme(legend.position = "none")

library(lattice)
xyplot(resid(m) ~ fitted(m)|PATIENTID, m@frame)
