require(lme4)
require(lmerTest)
require(ggplot2)
require(car)
require(perturb)
require(doBy)
require(Hmisc)
require(languageR)
require(effects)

data <- read.csv("out.txt")

data <- within(data, {
  CHANNEL <- as.factor(CHANNEL)
  EQUIVLDOPA <- EQUIVLDOPA/1000
  EQUIVLDOPA <- (EQUIVLDOPA - mean(EQUIVLDOPA,na.rm=T)) / sd(EQUIVLDOPA,na.rm=T)
  #    locAP <- (locAP - mean(locAP)) #/ sd(locAP)  
  #    locML <- (locML - mean(locML)) #/ sd(locML)  
  #    locDV <- (locDV - mean(locDV)) #/ sd(locDV)
})

data$CONDITION <- relevel(data$CONDITION,ref="ON")

lme0 = lmer(sqrt(f_4_8)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_8_12)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_12_20)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_20_30)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_60_90)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)

lme0 = lmer(sqrt(f_4_8)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_12_20)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_20_30)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_60_90)~ CONDITION + TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)

lme0 = lmer(sqrt(f_4_8)~ CONDITION*(TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND) + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_12_20)~ CONDITION*(TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND) + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_20_30)~ CONDITION*(TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND) + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)
lme0 = lmer(sqrt(f_60_90)~ CONDITION*(TREMOR_COND + BRADYKINESIA_COND + RIGIDITY_COND + AXIAL_COND) + locAP*locML*locDV + SIDE + (1|PATIENTID/SIDE/CHANNEL),data=data,REML=T)
summary(lme0)

qqPlot(resid(lme0), main="Q-Q plot for residuals")
plotLMER.fnc(lme0,pred="OFF",intr=list("CONDITION",c("OFF","ON"), NA))
#tapply(data$p, data$CONDITION, mean)
#plot(lme0,type=c("p","smooth"))
plot(lme0, resid(., scaled=TRUE) ~ fitted(.) | PATIENTID, abline = 0)
plot(lme0, resid(., scaled=TRUE) ~ fitted(.) | SIDE, abline = 0)
plot(lme0, sqrt(p) ~ fitted(.) | PATIENTID, abline = c(0,1))
plot(lme0, PATIENTID ~ resid(., scaled=TRUE))
fixeff.plotcorr(lme0)

plot(effect("UPDRSIV", lme0,partial.residuals=T))
plot(effect("CONDITION*TREMOR_CONTRA", lme0,partial.residuals=T))
plot(effect("locAP*locML*locDV", lme0,partial.residuals=T))
#plot(effect("locAP*locML*locDV", lme0,xlevels=list(locAP=seq(3,11,length.out=2),locML=seq(-3,7,length.out=2),locDV=seq(-3,9,length.out=2))))
