tf= tf_one; 
mean_ipsi_contra= mean_patient_mean_contra_ch_tf.values{1,1}./ mean_patient_mean_ipsi_ch_tf.values{1,1};
label= 'contra-ipsi';
 tf_mean_contra_ipsi= SpectralProcess(mean_ipsi_contra,...
'f',tf.f,...
'params',tf.params,...
'tBlock',tf.tBlock,...
'tStep',tf.tStep,...
'labels',label,...
'tStart',tf.relWindow(1),...
'tEnd',tf.relWindow(2)...
);
plot(tf_mean_contra_ipsi, 'colormap', 'jet', 'title', true, 'caxis', axis_length);