cd('/Users/brian.lau/CloudStation/Work/Production/Papers/2015_STN10Year/Data');
dat = ten.load.data();
clear SCORES scores;


q = linq();

vars = {'updrsIIOff' 'updrsIIOn'...
        'updrsIIIOffSOffM' 'updrsIIIOffSOnM' 'updrsIIIOnSOffM' 'updrsIIIOnSOnM'...
        'akinesiaOffSOffM' 'akinesiaOffSOnM' 'akinesiaOnSOffM' 'akinesiaOnSOnM'...
        'rigidityOffSOffM' 'rigidityOffSOnM' 'rigidityOnSOffM' 'rigidityOnSOnM'...
        'tremorOffSOffM' 'tremorOffSOnM' 'tremorOnSOffM' 'tremorOnSOnM'...
        'axeOffSOffM' 'axeOffSOnM' 'axeOnSOffM' 'axeOnSOnM' ...
        'updrsIV' 'DSK' 'OFF' ...
        'Mattis' 'ldopaEquiv'};
vis = 1;

for i = 1:numel(vars)
   temp0 = q(dat).select(@(x) x.visit(1).(vars{i})).toArray;
   temp1 = q(dat).select(@(x) x.visit(2).(vars{i})).toArray;
   temp2 = q(dat).select(@(x) x.visit(3).(vars{i})).toArray;
   temp5 = q(dat).select(@(x) x.visit(4).(vars{i})).toArray;
   temp10 = q(dat).select(@(x) x.visit(5).(vars{i})).toArray;

   fprintf('%s\t\t%1.2f(%1.2f)\t%1.2f(%1.2f)\t%1.2f(%1.2f)\t%1.2f(%1.2f)\t%1.2f(%1.2f)\n',vars{i},...
      nanmean(temp0),nanstd(temp0),nanmean(temp1),nanstd(temp1),nanmean(temp2),nanstd(temp2),...
      nanmean(temp5),nanstd(temp5),nanmean(temp10),nanstd(temp10));
  
end


%%
vars = {'akinesiaOffSOffM' 'akinesiaOffSOnM' 'akinesiaOnSOffM' 'akinesiaOnSOnM'...
        'rigidityOffSOffM' 'rigidityOffSOnM' 'rigidityOnSOffM' 'rigidityOnSOnM'...
        'tremorOffSOffM' 'tremorOffSOnM' 'tremorOnSOffM' 'tremorOnSOnM'...
        'axeOffSOffM' 'axeOffSOnM' 'axeOnSOffM' 'axeOnSOnM'};
% vars = {'akinesiaOffSOffM'...
%         'rigidityOffSOffM'...
%         'tremorOffSOffM'...
%         'axeOffSOffM'};

%      vars = {'akinesiaOffSOffM'...
%         'rigidityOffSOffM'...
%         'tremorOffSOffM'...
%         'axeOffSOffM'...
%         'hallucinations'...
%         'Mattis'};

mat = [];
varnames = {};
for i = 1:numel(vars)
   temp0 = q(dat).select(@(x) x.visit(1).(vars{i})).toArray;
   temp1 = q(dat).select(@(x) x.visit(2).(vars{i})).toArray;
   temp2 = q(dat).select(@(x) x.visit(3).(vars{i})).toArray;
   temp5 = q(dat).select(@(x) x.visit(4).(vars{i})).toArray;
   temp10 = q(dat).select(@(x) x.visit(5).(vars{i})).toArray;

   fprintf('%s\t\t%1.2f(%1.2f)\t%1.2f(%1.2f)\t%1.2f(%1.2f)\t%1.2f(%1.2f)\t%1.2f(%1.2f)\n',vars{i},...
      nanmean(temp0),nanstd(temp0),nanmean(temp1),nanstd(temp1),nanmean(temp2),nanstd(temp2),...
      nanmean(temp5),nanstd(temp5),nanmean(temp10),nanstd(temp10));
  
   mat = [mat , temp0' , temp1', temp2', temp5', temp10'];
   varnames = [varnames , [vars{i} '_t0'] [vars{i} '_t1'] [vars{i} '_t2'] [vars{i} '_t5'] [vars{i} '_t10']];
end

tab = array2table(mat,'VariableNames',varnames);

writetable(tab,'wide.txt')